#!/usr/bin/env bash
# Write public/_redirects so /mgmt-api and /game-api proxy to the same CKS env.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="${ROOT}/public/_redirects"

# Explicit override wins (no trailing slash).
MGMT_PROXY="${MANAGEMENT_API_PROXY_TARGET:-}"

if [[ -z "$MGMT_PROXY" && -n "${VITE_ENV_HANDLE:-}" ]]; then
  MGMT_PROXY="https://api.${VITE_ENV_HANDLE}.dev.cks-env.com"
fi

if [[ -z "$MGMT_PROXY" ]]; then
  MGMT_PROXY="https://api.dev.crowdedkingdoms.com"
fi

MGMT_PROXY="${MGMT_PROXY%/}"

GAME_PROXY="${GAME_API_PROXY_TARGET:-}"

if [[ -z "$GAME_PROXY" && -n "${VITE_ENV_HANDLE:-}" ]]; then
  GAME_PROXY="https://game.${VITE_ENV_HANDLE}.dev.cks-env.com"
fi

if [[ -z "$GAME_PROXY" ]]; then
  GAME_PROXY="https://game.dev.crowdedkingdoms.com"
fi

GAME_PROXY="${GAME_PROXY%/}"

cat > "$DEST" <<EOF
# Generated by scripts/generate-netlify-redirects.sh — do not edit by hand.
# force (!) so these win over the SPA catch-all
/mgmt-api/*  ${MGMT_PROXY}/:splat  200!
/game-api/*  ${GAME_PROXY}/:splat  200!

# SPA client-side routes (must be last)
/*           /index.html  200
EOF

echo "Wrote ${DEST} (mgmt → ${MGMT_PROXY}, game → ${GAME_PROXY})"
