#!/usr/bin/env bash
# Write public/_redirects for SPA fallback + dynamic CKS API proxy function.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="${ROOT}/public/_redirects"

cat > "$DEST" <<'EOF'
# Generated by scripts/generate-netlify-redirects.sh — do not edit by hand.
# Dynamic env proxy — forwards to any allowed CKS management/game GraphQL host.
/cks-proxy/mgmt*  /.netlify/functions/cks-proxy  200!
/cks-proxy/game*  /.netlify/functions/cks-proxy  200!

# SPA client-side routes (must be last)
/*                /index.html  200
EOF

echo "Wrote ${DEST} (cks-proxy → Netlify function)"
