#!/usr/bin/env bash
# Write public/_redirects so /mgmt-api proxies to the same CKS env as the game API.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="${ROOT}/public/_redirects"

# Explicit override wins (no trailing slash).
PROXY_TARGET="${MANAGEMENT_API_PROXY_TARGET:-}"

if [[ -z "$PROXY_TARGET" && -n "${VITE_ENV_HANDLE:-}" ]]; then
  PROXY_TARGET="https://api.${VITE_ENV_HANDLE}.dev.cks-env.com"
fi

if [[ -z "$PROXY_TARGET" ]]; then
  PROXY_TARGET="https://api.dev.crowdedkingdoms.com"
fi

PROXY_TARGET="${PROXY_TARGET%/}"

cat > "$DEST" <<EOF
# Generated by scripts/generate-netlify-redirects.sh — do not edit by hand.
# force (!) so these win over the SPA catch-all
/mgmt-api/*  ${PROXY_TARGET}/:splat  200!

# SPA client-side routes (must be last)
/*           /index.html  200
EOF

echo "Wrote ${DEST} (mgmt proxy → ${PROXY_TARGET})"
